#!/usr/bin/env python2

cmt = [-1] * 200


cmt[1] = "'There is always light behind the clouds. -- Louisa May Alcott'"
cmt[2] = "'Change before you have to. -- Jack Welch'"
cmt[3] = "'If you can dream it, you can do it. -- Walt Disney'"
cmt[4] = "'Love the life you live. Live the life you love. -- Bob Marley'"
cmt[5] = "\"My life didn't please me, so I created my life.-- Coco Chanel\""
cmt[6] = "\"It always seems impossible until it's done -- Nelson Mandela\""
cmt[7] = "'Peace begins with a smile. -- Mother Teresa'"
cmt[8] = "'Love dies only when growth stops. -- Pearl S. Buck'"
cmt[9] = "'There is more to life than increasing its speed. -- Mahatma Gandhi'"
cmt[10] = "'Everything is practice. -- Pele'"
cmt[11] = "'Men willingly believe what they wish. -- Julius Caesar'"
cmt[12] = "'If you want to be happy, be. -- Leo Tolstoy'"
cmt[13] = "'Without haste, but without rest. -- Johann Wolfgang von Goethe'"
cmt[14] = "\"You'll never find a rainbow if you're looking down. -- Charlie Chaplin\""
cmt[15] = "'Indecision is often worse than wrong action. -- Henry Ford'"
cmt[16] = "'He who has never hoped can never despair. -- George Bernard Shaw'"
cmt[17] = "'Love is more afraid of change than destruction. -- Friedrich Nietzsche'"
cmt[18] = "\"It's all about the journey, not the outcome. -- Carl Lewis\""
cmt[19] = "'I will prepare and some day my chance will come. -- Abraham Lincoln'"
cmt[20] = "'Do one thing everyday that scares you. -- Eleanor Roosevelt'"
cmt[21] = "'Some people feel the rain. Others just get wet. -- Bob Marley'"
cmt[22] = "\"I like to be a free spirit. Some don't like that, but that's the way I am -- Diana, Princess of Wales\""
cmt[23] = "'The man who has no imagination has no wings. -- Muhammad Ali'"
cmt[24] = "\"I don't dream at night, I dream all day; I dream for a living. -- Steven Spielberg\""
cmt[25] = "'To say Good bye is to die a little. -- Raymond Chandler'"
cmt[26] = "\"Don't walk behind me; I may not lead. Don't walk in front me; I may not follow. Just walk beside me and be my friend -- Albert Camus\""
cmt[27] = "\"I can accept failure, everyone fails at something. But I can't accept not trying. -- Michael Jordan\""
cmt[28] = "'Defeat? I do not recognize the meaning of the word. -- Margaret Thatcher'"
cmt[29] = "'I do not seek, I find. -- Pablo Picasso'"
cmt[30] = "'If I wasn't hard, I wouldn't be alive. If I couldn't ever be gentle, I wouldn't deserve to be alive. -- Raymond Chandler'"
cmt[31] = "'A woman does not became interesting until she is over 40. -- Coco Chanel'"
cmt[32] = "'We don't stop playing because we grow old; we grow old because we stop playing. -- George Bernard Shaw'"
cmt[33] = "'Before you point your fingers, make sure your hands are clean. -- Bob Marley'"
cmt[34] = "'Never, never, never, never give up. -- Winston Churchill'"
cmt[35] = "\"If you don't practice you don't deserve to win. -- Andre Agassi\""
cmt[36] = "\"You don't need any brains to listen to music. -- Luciano Pavarotti\""
cmt[37] = "\"Only the gentle are ever really strong. -- James Dean\""
cmt[38] = "\"I always looked ahead. -- Chris Evert\""
cmt[39] = "\"Living is not breathing but doing. -- Jean-Jacques Rousseau\""
cmt[40] = "\"You can't get away from yourself by moving from one place to another. -- Ernest Hemingway\""
cmt[41] = "\"It is not length of life, but depth of life. -- Ralph Waldo Emerson\""
cmt[42] = "\"This world is but a canvas to our imaginations. -- Henry David Thoreau\""
cmt[43] = "\"In the near future, I hope that we will be able to further the work that was started here. -- John Coltrane\""
cmt[44] = "\"Once I made a decision, I never thought about it again. -- Michael Jordan\""
cmt[45] = "\"Our life is our art. -- John Lennon\""
cmt[46] = "\"Art washes away from the soul the dust of everyday life. -- Pablo Picasso\""
cmt[47] = "\"All we're supposed to do, I feel, is try to make people happy. This is music that belongs to all of us, not just black or white - and I'm proud of it. -- Art Blakey\""
cmt[48] = "\"The real voyage of discovery consists not in seeking new landscapes, but in having new eyes. -- Marcel Proust\""
cmt[49] = "\"I keep my ideals, because in spite of everything I still believe that people are really good at heart. -- Anne Frank\""
cmt[50] = "\"I submit to you that if a man hasn't discovered something that he will die for, he isn't fit to live. -- Martin Luther King, Jr.\""
cmt[51] = "\"I have nothing to offer but blood, toil, tears, and sweat. -- Winston Churchill\""
cmt[52] = "\"I have done battle every single day of my life. -- Margaret Thatcher\""
cmt[53] = "\"Find purpose, the means will follow. -- Mahatma Gandhi\""
cmt[54] = "\"Do you want to spend the rest of your life selling sugared water, or do you want a chance to change the world? -- Steve Jobs\""
cmt[55] = "\"Whoever said, ''It's not whether you win or lose that counts,'' probably lost. -- Martina Navratilova\""
cmt[56] = "\"The best way to predict the future is to create it. -- Peter Drucker\""
cmt[57] = "\"Happiness does not lie in happiness, but in the achievement of it. -- Fyodor Dostoyevsky\""
cmt[58] = "\"Freedom is not worth having if it does not include the freedom to make mistakes. -- Mahatma Gandhi\""
cmt[59] = "\"A game is not won until it's lost. -- David Pleat\""
cmt[60] = "\"Dream as if you'll live forever, live as if you'll die today. -- James Dean\""
cmt[61] = "\"All we are saying is give peace a chance! -- John Lennon\""
cmt[62] = "\"A life is not important except in the impact it has on other lives. -- Jackie Robinson\""
cmt[63] = "\"Our greatest glory is not in never falling, but in rising up every time we fail. -- Ralph Waldo Emerson\""
cmt[64] = "\"It's been a long way, but we're here. -- Alan Shepard\"" 
cmt[65] = "\"Circumstances - what are circumstances? I make circumstances. -- Napoleon\""
cmt[66] = "\"Stay hungry. Stay foolish. -- Steve Jobs\""
cmt[67] = "\"Learn from the mistakes of others. You can't live long enough to make them all yourself. -- Eleanor Roosevelt\""
cmt[68] = "\"The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails. -- William Arthur Ward\""
cmt[69] = "\"Life can only be understood backwards; but it must be lived forwards. -- Soren Kierkegaard\""
cmt[70] = "\"God doesn't require us to succeed; he only requires that you try. -- Mother Teresa\""
cmt[71] = "\"Many of life's failures are people who did not realize how close they were to success when they gave up. -- Thomas A. Edison\""
cmt[72] = "\"Anyone who has never made a mistake has never tried anything new. -- Albert Einstein\""
cmt[73] = "\"Life isn't about finding yourself. Life is about creating yourself. -- George Bernard Shaw\""
cmt[74] = "\"It is not what we get. But who we become, what we contribute that gives meaning to our lives. -- Anthony Robbins\""
cmt[75] = "\"The purpose of life is a life of purpose. -- Robert Byrne\""
cmt[76] = "\"To live is to climb the Andes: the more one climbs, the steeper become the precipices. -- Eucenio Maria De Hostos\""
cmt[77] = "\"You can't get away from yourself by moving from one place to another. -- Ernest Hemingway\""
cmt[78] = "\"The greatest mistake you can make in life is be continually fearing you will make one. -- Elbert Hubbard\""
cmt[79] = "\"The most important thing is to enjoy your life - to be happy - It's all that matters. -- Audrey Hepbarn\""
cmt[80] = "\"An investment in knowledge always pays the best interest. -- Benjamin Franklin\""
cmt[81] = "\"What do you want meaning for ? Life is desire, not meaning. -- Charlie Chaplin\""
cmt[82] = "\"The snake which cannot cast its skin has to die. As well the minds which are prevented from changing their opinions; they cease to be mind. -- Friedrich Nietzche\""
cmt[83] = "\"For one swallow does not make a summer, nor does one day; and so too one day, or a short time, does not make a man blessed and happy. -- Aristotle\""
cmt[84] = "\"Man lives freely only by his readiness to die. -- Mahatma Gandhi\""
cmt[85] = "\"One's philosophy is not best expressed in words; it is expressed in the choices one makes ... and the choice we make are ultimately our responsibility. -- Eleanor Roosevelt\""
cmt[86] = "\"Life is what happens to you while you're busy making other plans. -- John Lennon\""
cmt[87] = "\"If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours. -- Henry David Thoreau\""
cmt[88] = "\"Real life is, to most men. a long second-best, a perpetual compromise between the ideal and the possible. -- Bertrand Russell\""
cmt[89] = "\"Life is not fair, get used to it. -- Bill Gates\""
cmt[90] = "\"Life is not complex. We are complex. Lfe is simple, and the simple thing is the right thing. -- Oscar Wilde\""
cmt[91] = "\"The greatest glory in living lies not in never falling, but in rising ever time we fall. -- Nelson Mandela\""
cmt[92] = "\"He is the happiest, be he king or peasant, who finds peace in his home. -- Johann Wolfgang von Goethe\""
cmt[93] = "\"In three words I can sum up everything I've learned about life: it goes on. -- Robert Frost\""
cmt[94] = "\"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. -- Ralph Waldo Emerson\""
cmt[95] = "\"Life is like riding a bicycle. To keep your balance you must keep moving. -- Albert Einstein\""
cmt[96] = "\"Where there's hope, there's life. It fills us with fresh courage and makes us strong again. -- Anne Frank\""
cmt[97] = "\"To play billiards moderately well is the sign of a gentleman; to play it too well is the sign of a misspent life. -- Mark Twain\""
cmt[98] = "\"Life was meant to be lived, and curiosity must be kept alive. One must never, for whatever reason, turn his back on life. -- Eleanor Roosevelt\""
cmt[99] = "\"Take a chance! All life is a chance. The man who goes the farthest is generally the one who is willing to do and dare. -- Dale Carnegie\""
cmt[100] = "\"I count him braver who overcomes his desires than him who conquers his enemies; for the hardest victory is over self. -- Aristotle\""
cmt[101] = "\"There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. -- Albert Einstein\""
cmt[102] = "\"Success is most often achieved by those who don't know that failure is inevitable. -- Coco Chanel\""
cmt[103] = "\"Life is an exciting business and most exciting when it is lived for others. -- helen keller\""
cmt[104] = "\"One thing life has taught me: If you are interested, you never have to look for new interests. They come to you. When you are genuinely interested in one thing, it will always lead to something else. -- Elenor Roosevelt\""
cmt[105] = "\"A successful man cannot realize how hard an unsuccessful man finds life. -- E. W. Howe\""
cmt[106] = "\"Most people are other people. Their thoughts are someone else's opinions, their lives a mimicry, their passions a quotation. -- Oscar Wilde\""
cmt[107] = "\"Life shouldn't be printed on dollar bills. -- Clifford Odets\""
cmt[108] = "\"I can think of nothing less pleasurable than a life devoted to pleasure. -- John D. Rockfeller, Jr.\""
cmt[109] = "\"Only put off until tomorrow what you are willing to die having left undone. -- Pablo Picasso\""
cmt[110] = "\"Try not to become a man of success but rather to become a man of value. -- Albert Einstein\""
cmt[111] = "\"The greatest happiness of life is the conviction that we are loved - loved for ourselves, or rather, loved in spite of ourselves. -- Victor Hugo\""
cmt[112] = "\"What can you do to promote world peace? Go home and love your family. -- Mother Teresa\""
cmt[113] = "\"The greatest use of life is spend it for something that will outlast it. -- William James\""

#-------------------------------------------------------
# http://iyashitour.com/meigen/eigo_meigen/eigo_life/4


for i in cmt:
    if i != -1: print i

# C-x r o
# C-x r d
